### PR TITLE
Followup

### PR DESCRIPTION
**Pull request by catap**
Here a few trivial changes.
 - remove warning from hugo-v0.121.1;
 - add the way to disable "power by" without hacking template.

### CODE REVIEW

**Comment by kaisugi** [comment]
sounds good!
I'm traveling abroad so I'll check this when I go home a few days later
(Also, it would be nicer to attach your comment when you finalize this pull request~

**Comment by catap** [comment]
ooops, the last commit shouldn't be here. Removed.

**Comment by catap** [comment]
and I just realized that here need one more things: link for legal page

**Comment by catap** [comment]
I'll keep PR as draft until I'm ready and active that I'd like to have here.

**Comment by catap** [comment]
Pushed all my thought for now.

This is deployed at https://kirill.korins.ky 

I'm happy with this theme. Thanks!

**Comment by catap** [comment]
Anyway, TOC is broken, and I have no idea how to fix it :(

**Review by kaisugi — APPROVED** [review]
LGTM

**Pull request merged**
